# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-03 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180703_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='User',
        ),
    ]
