# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-07 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(upload_to='org/%Y/%m', verbose_name='\u673a\u6784\u56fe\u7247'),
        ),
    ]
