# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-07 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180707_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='desc',
        ),
    ]
