# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-07 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_courseorg_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('pxjg', '\u57f9\u8bad\u673a\u6784'), ('person', '\u4e2a\u4eba'), ('gx', '\u9ad8\u6821')], default='pxjg', max_length=30, verbose_name='\u673a\u6784\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='desc',
            field=models.TextField(default='', verbose_name='\u673a\u6784\u7684\u63cf\u8ff0'),
        ),
    ]
