# -*- coding: utf-8 -*-
"""
Django settings for MxOnline project.

Generated by 'django-admin startproject' using Django 1.9.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# 这样做的用途是将extra_apps --mark,就可以直接当做根搜素路径了
sys.path.insert(0, os.path.join(BASE_DIR, "extra_apps"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'y%e@^n!^hb1h%3j4^4(v*k4ssm(16@%)8gd$yu#vzl_gdwk4i%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# 自定义的登录校验接口,其实都是返回的数据库中的object
AUTHENTICATION_BACKENDS = (
    'users.views.CustomBackend',
)

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',  # 自带的admin后台管理app
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'courses',
    'organization',
    'operation',
    'xadmin',  # xadmin app 更加强大的后台管理系统
    'crispy_forms',  # 也是xadmin依赖的
    'captcha',  # 用来做图片验证码的app
    'pure_pagination',  # 用来做分页功能的库
]


# 重载方法，因为继承的是django默认的auth_user类
AUTH_USER_MODEL = "users.User"

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # 在这一个中间件中就处理了sessions信息
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MxOnline.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.media',  # 这个配置让前端能获取到media下的图片，注册到前端页面
            ],
        },
    },
]

WSGI_APPLICATION = 'MxOnline.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mxonline',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',
        "init_command":"SET foreign_key_checks = 0;",  # 这一句的作用是取消外键约束，当外键不存在的时候仍然可以进行操作
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'zh-hans'  # 语言为中文

TIME_ZONE = 'Asia/Shanghai'   # 时区改为上海，默认UTC

USE_I18N = True

USE_L10N = True

USE_TZ = False  # 在数据库存储时不使用UTC时间，使用本地时间


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# media 文件
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#---------------------邮件发送配置begin——————————————————#
EMAIL_HOST = "smtp.sina.com"  # SMTP服务器：smtp.sina.com
EMAIL_PORT = 25
EMAIL_HOST_USER = "lukes_zxs@sina.com"  # django登录这个邮箱发邮件
EMAIL_HOST_PASSWORD = "qq707115"
EMAIL_USE_TLS = False
EMAIL_FROM = "lukes_zxs@sina.com"
#---------------------邮件发送配置  end——————————————————#